### ISSUE TITLE
Error while using generate method

### ISSUE THREAD

**Issue by kerunaru** [apeiros/iso-iban#5]
```
irb(main):005:0* ISO::IBAN.generate('ES', '2077002400', '3102575766')
NoMethodError: undefined method `rjust' for nil:NilClass
    from /var/lib/gems/2.1.0/gems/iso-iban-0.1.3/lib/iso/iban/no_autoload.rb:220:in `block in generate'
    from /var/lib/gems/2.1.0/gems/iso-iban-0.1.3/lib/iso/iban/no_autoload.rb:220:in `map'
    from /var/lib/gems/2.1.0/gems/iso-iban-0.1.3/lib/iso/iban/no_autoload.rb:220:in `generate'
    from (irb):5
    from /var/lib/gems/2.1.0/gems/railties-4.1.8/lib/rails/commands/console.rb:90:in `start'
    from /var/lib/gems/2.1.0/gems/railties-4.1.8/lib/rails/commands/console.rb:9:in `start'
    from /var/lib/gems/2.1.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:69:in `console'
    from /var/lib/gems/2.1.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /var/lib/gems/2.1.0/gems/railties-4.1.8/lib/rails/commands.rb:17:in `<top (required)>'
    from /var/lib/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
    from /var/lib/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
    from /var/lib/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /var/lib/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
    from /home/juanma/Proyectos/flexnet2/bin/rails:8:in `<top (required)>'
    from /var/lib/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
    from /var/lib/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `block in load'
    from /var/lib/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /var/lib/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
    from /var/lib/gems/2.1.0/gems/spring-1.2.0/lib/spring/commands/rails.rb:6:in `call'
    from /var/lib/gems/2.1.0/gems/spring-1.2.0/lib/spring/command_wrapper.rb:38:in `call'
    from /var/lib/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:183:in `block in serve'
    from /var/lib/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:156:in `fork'
    from /var/lib/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:156:in `serve'
    from /var/lib/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
    from /var/lib/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
    from /var/lib/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
    from /var/lib/gems/2.1.0/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'irb(main):006:0> 
```

EDIT:

After some research, I've discovered the problem was, for ES accounts, iso-iban is expecting three parameters besides the country code... Maybe iso-iban should raise a self-explanatory exception.

**Comment by kerunaru** [comment]
Ok. Ignore my last comment. I've found the `branch_code` method :)
